DefaultContentLanguage = "en"
Paginate = 100
SectionPagesMenu = "main"
baseURL = "/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
resourceDir = "../resources"
theme = "ananke"
title = "Warner Share Point"
[languages.en]
contentDir = "content/en"
title = "Warner Share Point"
weight = 1
[params]
author = ""
background_color_class = "bg-mid-gray"
description = "Make Your Mark"
favicon = ""
recent_posts_number = 3
site_logo = ""
text_color = ""
[[params.ananke_socials]]
name = "twitter"
url = "mailto:kylewarner@mailstack.com"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
