baseURL = '/'
languageCode = 'en-us'
title = 'Warner Share Point'
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 100 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Warner Share Point"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
name = "Humor"
url = "tags/humor/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Make Your Mark"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "mailto:kylewarner@mailstack.com"
